### ISSUE TITLE
What changes should be made to Actnet when backbone is eption xception?

### ISSUE THREAD

**Issue by longmalongma** [yuk6heo/IVOS-ATNet#5]
What changes should be made to Actnet when backbone is eption xception? If backbone is xception, how do I get R5, R4, R3, and R2?

![image](https://user-images.githubusercontent.com/40291722/128542900-9a386232-27c4-4b73-a4f9-8a7b8f5099bd.png)

**Comment by yuk6heo** [comment]
I'm not sure what is your exact intentions,
but it can be replaced with the features which have same resolution and channels in a whole model.
